/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   gettingStartedSidebar: [{type: 'autogenerated', dirName: '.'}],
// };


/*
Get Your CITROS
Getting started: (CITROS CLI)
organize your work (Overview)
Install 
Run 
File System
  Locate your work
  Set Params
  Check more?


Peel your CITROS
Web - Beutify your work
Overview
Features
  Sort
  Filter
  Choose Params

Share your CITROS
  Overview
  Account Management
    Register
    update users (invite, delete)
    Type of licenses
    Set Useere roles
    update permissions
  Account Billing
    Manage subscription
    View Invoices
    Edit Billig info

  
  make Lemonade
    Collaborate your work
    Sync your data
    Multiple Run
    Analyse your data



*/

module.exports = {
  gettingStartedSidebar: [
    {
      type: 'category',
      label: 'Get Your CITROS',
      // link: {
                // type: 'doc',
                // id: "index",
              // },  
      collapsible: true,
      collapsed: true,
       items: [
        {
          type: 'doc',
          id: 'getting_started',
        },
        {
          type: 'doc',
          id: 'organize_your_work',
        },
        {
          type: 'doc',
          id: 'install',
        },
        {
          type: 'doc',
          id: 'run',
          // label: 'Examples',
        },
        {
          type: 'category',
          label: 'File System',
          items: [
            {
              type: 'doc',
              id: 'locate_work',
            },
            {
              type: 'doc',
              id: 'set_params',
            },
          ]
        },
      ],
    },
    {
      type: 'category',
      label: 'Peel Your CITROS',
      // link: {
                // type: 'doc',
                // id: "index",
              // },  
      collapsible: true,
      collapsed: true,
       items: [
        {
          type: 'doc',
          id: 'beautify',
        },
        {
          type: 'doc',
          id: 'web_overview',
        },
        {
          type: 'category',
          label: 'Features',
          items: [
            {
              type: 'doc',
              id: 'sort',
            },
            {
              type: 'doc',
              id: 'filter',
            },
            {
              type: 'doc',
              id: 'choose_params',
            },
          ]
        },
       ]
    },
    {
      type: 'category',
      label: 'Share Your CITROS',
      collapsible: true,
      collapsed: true,
       items: [
        {
          type: 'doc',
          id: 'overview',
        },
        {
          type: 'category',
          label: 'Account Management',
          items: [
            {
              type: 'doc',
              id: 'register',
            },
            {
              type: 'doc',
              id: 'update_users',
            },
            {
              type: 'doc',
              id: 'licenses',
            },
            {
              type: 'doc',
              id: 'roles',
            },
            {
              type: 'doc',
              id: 'permissions',
            },
          ]
        },
        {
          type: 'category',
          label: 'Account Billing',
          items: [
            {
              type: 'doc',
              id: 'manage_sub',
            },
            {
              type: 'doc',
              id: 'view_invoices',
            },
            {
              type: 'doc',
              id: 'edit',
            },
          ]
        },
       ]
    },
    {
      type: 'category',
      label: 'Make Lemonnade',
      collapsible: true,
      collapsed: true,
       items: [
        {
          type: 'doc',
          id: 'collaborate',
        },
        {
          type: 'doc',
          id: 'sync',
        },
        {
          type: 'doc',
          id: 'multirun',
        },
        {
          type: 'category',
          label: 'Analyse Your Data',
          items: [
            {
              type: 'category',
              label: 'Data access',
              items: [
                {
                  type: 'link',
                  label: 'Data Access Examples',
                  href: '/docs_data_analysis/data_access_examples',
                  // label: 'Examples',
                },
                {
                  type: 'link',
                  label: 'Data Access',
                  href: '/documentation/data_access',
                  // label: 'Examples',
                },
              ]
            },
            {
              type: 'category',
              label: 'Error Analysis',
              items: [
                {
                  type: 'link',
                  label: 'Error Analysis Examples',
                  href: '/docs_data_analysis/error_analysis_examples',
                  // label: 'Documentation',
                },
                {
                  type: 'link',
                  label: 'Error Analysis',
                  href: '/documentation/error_analysis',
                  // label: 'Examples',
                },
              ],
            },
            {
              type: 'category',
              label: 'Validation',
              items: [
                {
                  type: 'link',
                  label: 'Validation_examples',
                  href: '/docs_data_analysis/validation_examples',
                  // label: 'Documentation',
                },
                {
                  type: 'link',
                  label: 'Validation',
                  href: '/documentation/validation',
                  // label: 'Documentation',
                }
              ],
            },
          ]
        },

       ]
    }
  ],
};


