/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   gettingStartedSidebar: [{type: 'autogenerated', dirName: '.'}],
// };

module.exports = {
  gettingStartedSidebar: [
    {
      type: 'category',
      label: '///',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'doc',
          label: 'TBD',
          id: 'dummy',
        },
      ],
    },

    {
      type: 'category',
      label: 'CITROS CLI',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'dummy',
        },
        {
          type: 'doc',
          label: 'Installation',
          id: 'dummy',
        },
        {
          type: 'category',
          label: 'CLI API Commands',
          items: [
            {
              type: 'doc',
              label: 'Initialisation',
              id: 'dummy',
            },
            {
              type: 'doc',
              label: 'Account Commands',
              id: 'dummy',
            },
            {
              type: 'doc',
              label: 'Remote Repository Commands',
              id: 'dummy',
            },
            {
              type: 'doc',
              label: 'Simulations Commands',
              id: 'dummy',
            },
            {
              type: 'doc',
              label: 'CI/CD Commands',
              id: 'dummy',
            },
          ]
        },
        {
          type: 'doc',
          label: 'Project Configuration',
          id: 'dummy',
        },
      ],
    },



    {
      type: 'category',
      label: 'Authentication',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Account',
          items: [
            {
              type: 'doc',
              label: 'Registraion Login',
              id: 'authentication/account/account_login',
            },
            {
              type: 'doc',
              label: 'Change Password',
              id: 'authentication/account/account_password',
            },
            {
              type: 'category',
              label: 'Profile Settings',
              items: [

                {
                  type: 'doc',
                  label: 'Notification Settings',
                  id: 'authentication/profile/notification_settings',
                },
                {
                  type: 'doc',
                  label: 'SSH Keys',
                  id: 'authentication/profile/ssh',
                },
                {
                  type: 'doc',
                  label: 'Quota',
                  id: 'authentication/profile/quota',
                },




              ]
            },
          ]
        },
        {
          type: 'category',
          label: 'SSH Keys',
          items: [
            {
              type: 'category',
              label: 'Connect with SSH',
              items: [
                {
                  type: 'doc',
                  label: 'Overview',
                  id: 'authentication/ssh/ssh_overview',
                },
                {
                  type: 'doc',
                  label: 'SSH Agent Forwarding',
                  id: 'authentication/ssh/ssh_agent_forwarding',
                },
                {
                  type: 'doc',
                  label: 'Generate new SSH Key',
                  id: 'authentication/ssh/ssh_generate_key',
                },
                {
                  type: 'doc',
                  label: 'Test your SSH connection',
                  id: 'authentication/ssh/ssh_test_connection',
                },
                {
                  type: 'doc',
                  label: 'SSH key passphrases',
                  id: 'authentication/ssh/ssh_passphrases',
                }
              ]
            },
            {
              type: 'category',
              label: 'Troubleshooting',
              items: [
                {
                  type: 'doc',
                  label: 'SSH key passphrases',
                  id: 'authentication/troubleshooting/ts_passphrases',
                },
                {
                  type: 'doc',
                  label: 'Deleted or Missing SSH Keys',
                  id: 'authentication/troubleshooting/ts_missing_key',
                },
                {
                  type: 'doc',
                  label: 'Errors',
                  id: 'authentication/troubleshooting/ts_error',
                },
                {
                  type: 'doc',
                  label: 'Permission Denied',
                  id: 'authentication/troubleshooting/ts_permissions',
                }
              ]
            },
          ]
        },
      ],
    },





    {
      type: 'category',
      label: 'Billing',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'doc',
          label: 'Payment Method',
          id: 'billing/billing_pm',
        },
        {
          type: 'doc',
          label: 'Billing Address',
          id: 'billing/billing_address',
        },
        {
          type: 'doc',
          label: 'Invoices',
          id: 'billing/billing_invoices',
        },
        {
          type: 'doc',
          label: 'Plans',
          id: 'billing/billing_plans',
        },
      ],
    },

    {
      type: 'category',
      label: 'Notifications',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'doc',
          label: 'Notification Template',
          id: 'dummy',
        },
        {
          type: 'doc',
          label: 'Notification Settings',
          id: 'dummy',
        },
      ],
    },



    {
      type: 'category',
      label: 'Simulations',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'simulations/sim_overview',
        },
        {
          type: 'category',
          label: 'Batch Simulations',
          items: [
            {
              type: 'doc',
              label: 'Breadcrumbs',
              id: 'simulations_batch/sim_batch_breadcrumbs',
            },
            {
              type: 'doc',
              label: 'Run New Batch Simulations',
              id: 'simulations_batch/sim_batch_run',
            },
            {
              type: 'doc',
              label: 'Batch Simulations Screen',
              id: 'simulations_batch/sim_batch_screen',
            },
          ]
        },
        {
          type: 'category',
          label: 'Simulation Screen',
          items: [
            {
              type: 'doc',
              label: 'Breadcrumbs',
              id: 'simulation_screen/sim_breadcrumbs',
            },
            {
              type: 'doc',
              label: 'Possible Runs',
              id: 'simulation_screen/sim_possible_runs',
            },
            {
              type: 'doc',
              label: 'Logs',
              id: 'simulation_screen/sim_logs',
            },
          ]
        },
      ],
    },
    {
      type: 'category',
      label: 'Repositories',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'repos/repos_overview',
        },
        {
          type: 'doc',
          label: 'Add Repository',
          id: 'repos/repos_add',
        },
        {
          type: 'doc',
          label: 'Repository Template',
          id: 'repos/repos_template',
        },
        {
          type: 'category',
          label: 'Repository File Structure',
          items: [
            {
              type: 'doc',
              label: 'Overview',
              id: 'repos_file_structure/repos_fs_overview',
            },
            {
              type: 'doc',
              label: 'citros_repo_id',
              id: 'repos_file_structure/repos_fs_repo_id',
            },
            {
              type: 'doc',
              label: 'notebooks',
              id: 'repos_file_structure/repos_fs_notebooks',
            },
            {
              type: 'doc',
              label: 'parameter_setup',
              id: 'repos_file_structure/repos_fs_param_setup',
            },
            {
              type: 'doc',
              label: 'project.json',
              id: 'repos_file_structure/repos_fs_project_json',
            },
            {
              type: 'doc',
              label: 'readme',
              id: 'repos_file_structure/repos_fs_readme',
            },
            {
              type: 'doc',
              label: 'reports',
              id: 'repos_file_structure/repos_fs_reports',
            },
            {
              type: 'doc',
              label: 'settings.json',
              id: 'repos_file_structure/repos_fs_settings_json',
            },
            {
              type: 'doc',
              label: 'simulations',
              id: 'repos_file_structure/repos_fs_simulations',
            },
            {
              type: 'doc',
              label: 'user_commit',
              id: 'repos_file_structure/repos_fs_user_commit',
            },
            {
              type: 'doc',
              label: 'workflows',
              id: 'repos_file_structure/repos_fs_workflows',
            },
          ]
        },
      ],
    },
    {
      type: 'category',
      label: 'Data Analysis',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'data_analysis',
        },
        {
          type: 'category',
          label: 'Data access',
          items: [
            {
              type: 'link',
              label: 'Overview',
              href: '/docs_data_analysis/index_data_access',
            },
            {
              type: 'link',
              label: 'Data Access Examples',
              href: '/docs_data_analysis/data_access_examples',
              // label: 'Examples',
            },
            {
              type: 'link',
              label: 'Data Access API',
              href: '/documentation/data_access',
              // label: 'Examples',
            },
          ]
        },
        {
          type: 'category',
          label: 'Error Analysis',
          items: [
            {
              type: 'link',
              label: 'Overview',
              href: '/docs_data_analysis/index_data_access',
            },
            {
              type: 'link',
              label: 'Error Analysis Examples',
              href: '/docs_data_analysis/error_analysis_examples',
              // label: 'Documentation',
            },
            {
              type: 'link',
              label: 'Error Analysis API',
              href: '/documentation/error_analysis',
              // label: 'Examples',
            },
          ],
        },
        {
          type: 'category',
          label: 'Validation',
          items: [
            {
              type: 'link',
              label: 'Overview',
              href: '/docs_data_analysis/index_data_access',
            },
            {
              type: 'link',
              label: 'Validation_examples',
              href: '/docs_data_analysis/validation_examples',
              // label: 'Documentation',
            },
            {
              type: 'link',
              label: 'Validation API',
              href: '/documentation/validation',
              // label: 'Documentation',
            }
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Organization',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'doc',
          label: 'TBD',
          id: 'dummy',
        },
      ],
    },
    {
      type: 'category',
      label: 'CI/CD and DevOps',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'doc',
          label: 'TBD',
          id: 'dummy',
        },
      ],
    }
  ]
};