// module.exports = {
//   tutorialSidebar: [
//     {
//       type: 'category',
//       label: 'Tutorials',
//       link: {
//         type: 'doc',
//         id: "index",
//       },
//       items: [
      
//             {
//               type: 'doc',
//               id: 'lunar_hopper/lunar_hopper',
//               // label: 'Examples',
//             },
//             {
//               type: 'doc',
//               id: 'Lunar_starship/Lunar_starship',
//               // label: 'Examples',
//             },
//             {
//               type: 'doc',
//               id: 'mass_spring/mass_spring',
//               // label: 'Examples',
//             },
//             {
//               type: 'doc',
//               id: 'poliastro/poliastro',
//               // label: 'Examples',
//             },
//             {
//               type: 'doc',
//               id: 'turtlebot/turtlebot',
//               // label: 'Examples',
//             },
//           ]
//         },
//       ]
//     }

    module.exports = {
      tutorialSidebar: [
        {
          type: 'autogenerated',
          dirName: '.', // '.' means the current docs folder
        },
      ],
    };