module.exports = {
  citrosSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

// module.exports = {
//   docscli: [
//     { type: "doc", id: "index" },
//     {
//       type: 'doc',
//       id: 'examples/examples',
//       label: 'Examples',
//     },
//     {
//       type: 'doc',
//       id: 'documentations/documentations',
//       label: 'Documentation',
//     },
//   ],
// };