/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "CITROS",
  "tagline": "The starting point for your next robotic project",
  "favicon": "img/favicon.ico",
  "url": "http://localhost:3000",
  "baseUrl": "/doc/",
  "organizationName": "citros",
  "projectName": "citros",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "markdown": {
    "mermaid": true
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "path": "docs",
          "sidebarPath": "/workspaces/citros_doc/sidebars.js"
        },
        "blog": {
          "showReadingTime": true
        },
        "theme": {
          "customCss": "/Users/vovacooper/dev/citros/citros/citros_doc/src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "docs-citros",
        "path": "docs-citros",
        "routeBasePath": "docs-citros",
        "sidebarPath": "/workspaces/citros_doc/sidebars.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "docs-cli",
        "path": "docs-cli",
        "routeBasePath": "docs-cli",
        "sidebarPath": "/workspaces/citros_doc/sidebars.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "docs-data-analysis",
        "path": "docs-data-analysis",
        "routeBasePath": "docs-data-analysis",
        "sidebarPath": "/workspaces/citros_doc/sidebars.js"
      }
    ]
  ],
  "stylesheets": [
    {
      "href": "/katex/katex.min.css",
      "type": "text/css"
    }
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "logo": {
        "alt": "CITROS Logo",
        "src": "img/citros.png"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "gettingStartedSidebar",
          "label": "Getting started",
          "position": "left",
          "activeBaseRegex": "/docs/"
        },
        {
          "to": "/docs-citros",
          "label": "Citros",
          "position": "left",
          "activeBaseRegex": "/docs-citros/"
        },
        {
          "to": "/docs-cli",
          "label": "CLI",
          "position": "left",
          "activeBaseRegex": "/docs-cli/"
        },
        {
          "to": "/docs-data-analysis",
          "label": "Data analysis",
          "position": "left",
          "activeBaseRegex": "/docs-data-analysis/"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "type": "docsVersionDropdown",
          "position": "right",
          "dropdownItemsAfter": [
            {
              "to": "/versions",
              "label": "All versions"
            }
          ],
          "dropdownActiveClassDisabled": true,
          "dropdownItemsBefore": []
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Tutorials",
          "items": [
            {
              "label": "Getting started",
              "to": "/docs"
            },
            {
              "label": "Citros",
              "to": "/docs-citros"
            },
            {
              "label": "CLI",
              "to": "/docs-cli"
            },
            {
              "label": "Data analysis",
              "to": "/docs-data-analysis"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Blog",
              "to": "/blog"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2023 My Project, Inc. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
