name: copy docs from data_analysis branch
on: 
  push:
    branches: 
      - autogen_data_analysis.*
  # workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get_version
        run: |
          echo ${{ github.ref_name }}
          version=$(echo ${{ github.ref_name }} | grep -oP '(?<=autogen_data_analysis.).*')
          echo "version=$version" >> "$GITHUB_ENV"
          echo "branch_name=${{ github.ref_name }}" >> "$GITHUB_ENV"

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: main 

      - name: make new doc version
        run: |
          git fetch
          git rm -r docs-data-analysis/*
          git checkout origin/${{ env.branch_name }} docs-data-analysis
          yarn install
          yarn docusaurus docs:version:docs-data-analysis ${{ env.version }}

      - name: 
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "update docs-data-analysis"
          git push origin main

      - name: delete branch
        run: git push origin --delete ${{ env.branch_name }}

      - name: Repository Dispatch
        # if: steps.verify_diff.outputs.changed == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: event_main_push