name: copy docs from data_analysis branch
on: 
  push:
    branches: 
      - autogen_data_analysis.*
  # workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get_version
        run: |
          echo ${{ github.ref_name }}

     #     change autogen_data_analysis:
          version=$(echo ${{ github.ref_name }} | grep -oP '(?<=autogen_data_analysis.).*')
          
          echo "version=$version" >> "$GITHUB_ENV"
          echo "branch_name=${{ github.ref_name }}" >> "$GITHUB_ENV"

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          # ref: main      #
          ref: test_result 

      - name: froze the previous version
      - name: copy folder
        run: |
         echo | ls
         git fetch
         git rm -r docs-data-analysis/*
         git checkout origin/docs-data-analysis docs-data-analysis
         yarn docusaurus docs-data-analysis:version "${{ env.version }}"
         git config --global user.email "actions@github.com"
         git config --global user.name "GitHub Actions"
        #  git diff
         git add -A
         git commit -m "update docs-data-analysis"
        #  git push origin main
         git push origin test_result

      - name: delete branch
        run: git push origin --delete ${{ env.branch_name }}